// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Major Code Smell", "S6966:Awaitable method should be used", Justification = "<Pending>", Scope = "member", Target = "~M:ShareMyAdventures.Application.UseCases.Adventures.Queries.ListWithPagingAdventuresByStatusIdQueryHandler.Handle(ShareMyAdventures.Application.UseCases.Adventures.Queries.ListWithPagingAdventuresByStatusIdQuery,System.Threading.CancellationToken)~System.Threading.Tasks.Task{ShareMyAdventures.Application.Common.Models.Result{ShareMyAdventures.Application.Common.Models.PagedData{ShareMyAdventures.Application.UseCases.Adventures.Queries.AdventureView}}}")]
[assembly: SuppressMessage("Major Code Smell", "S6966:Awaitable method should be used", Justification = "<Pending>", Scope = "member", Target = "~M:ShareMyAdventures.Application.UseCases.AdventureInvitations.Queries.GetInvitationsQueryHandler.Handle(ShareMyAdventures.Application.UseCases.AdventureInvitations.Queries.ListWithPagingInvitationsByUserIdQuery,System.Threading.CancellationToken)~System.Threading.Tasks.Task{ShareMyAdventures.Application.Common.Models.Result{ShareMyAdventures.Application.Common.Models.PagedData{ShareMyAdventures.Application.UseCases.AdventureInvitations.Queries.InvitationView}}}")]
[assembly: SuppressMessage("Major Code Smell", "S6966:Awaitable method should be used", Justification = "<Pending>", Scope = "member", Target = "~M:ShareMyAdventures.Application.UseCases.Adventures.Queries.GetAdventureQueryHandler.Handle(ShareMyAdventures.Application.UseCases.Adventures.Queries.GetAdventureByIdQuery,System.Threading.CancellationToken)~System.Threading.Tasks.Task{ShareMyAdventures.Application.Common.Models.Result{ShareMyAdventures.Application.UseCases.Adventures.Queries.AdventureView}}")]
[assembly: SuppressMessage("Major Code Smell", "S6966:Awaitable method should be used", Justification = "<Pending>", Scope = "member", Target = "~M:ShareMyAdventures.Application.UseCases.Search.Queries.SearchQueryHandler.Handle(ShareMyAdventures.Application.UseCases.Search.Queries.SearchQuery,System.Threading.CancellationToken)~System.Threading.Tasks.Task{ShareMyAdventures.Application.UseCases.Search.Queries.SearchResponse}")]
[assembly: SuppressMessage("Major Code Smell", "S6966:Awaitable method should be used", Justification = "<Pending>", Scope = "member", Target = "~M:ShareMyAdventures.Application.UseCases.Search.Queries.SearchQueryHandler.Handle(ShareMyAdventures.Application.UseCases.Search.Queries.SearchQuery,System.Threading.CancellationToken)~System.Threading.Tasks.Task{ShareMyAdventures.Application.Common.Models.Result{ShareMyAdventures.Application.Common.Models.PagedData{ShareMyAdventures.Application.UseCases.Search.Queries.SearchView}}}")]
[assembly: SuppressMessage("Major Code Smell", "S6966:Awaitable method should be used", Justification = "<Pending>", Scope = "member", Target = "~M:ShareMyAdventures.Application.UseCases.Friends.Queries.ListWithPagingFriendsQueryHandler.Handle(ShareMyAdventures.Application.UseCases.Friends.Queries.ListWithPagingFriendsQuery,System.Threading.CancellationToken)~System.Threading.Tasks.Task{ShareMyAdventures.Application.UseCases.Friends.Queries.ListWithPagingFriendsResponse}")]
[assembly: SuppressMessage("Major Code Smell", "S6966:Awaitable method should be used", Justification = "<Pending>", Scope = "member", Target = "~M:ShareMyAdventures.Application.UseCases.Friends.Queries.ListWithPagingFriendsQueryHandler.Handle(ShareMyAdventures.Application.UseCases.Friends.Queries.ListWithPagingFriendsQuery,System.Threading.CancellationToken)~System.Threading.Tasks.Task{ShareMyAdventures.Application.Common.Models.Result{ShareMyAdventures.Application.Common.Models.PagedData{ShareMyAdventures.Application.UseCases.Friends.Queries.FriendView}}}")]
[assembly: SuppressMessage("Major Code Smell", "S6966:Awaitable method should be used", Justification = "<Pending>", Scope = "member", Target = "~M:ShareMyAdventures.Application.UseCases.Friends.Queries.ListWithPagingFriendRequestsQueryHandler.Handle(ShareMyAdventures.Application.UseCases.Friends.Queries.ListWithPagingFriendRequestsQuery,System.Threading.CancellationToken)~System.Threading.Tasks.Task{ShareMyAdventures.Application.Common.Models.Result{ShareMyAdventures.Application.Common.Models.PagedData{ShareMyAdventures.Application.UseCases.Friends.Queries.FriendRequestView}}}")]
[assembly: SuppressMessage("Major Code Smell", "S6966:Awaitable method should be used", Justification = "<Pending>", Scope = "member", Target = "~M:ShareMyAdventures.Application.UseCases.Positions.Queries.ListForAdventureQueryHandler.Handle(ShareMyAdventures.Application.UseCases.Positions.Queries.GetLatestForAdventureQuery,System.Threading.CancellationToken)~System.Threading.Tasks.Task{ShareMyAdventures.Application.Common.Models.Result{System.Collections.Generic.IReadOnlyList{ShareMyAdventures.Application.UseCases.Positions.Queries.PositionView}}}")]
[assembly: SuppressMessage("Major Code Smell", "S6966:Awaitable method should be used", Justification = "<Pending>", Scope = "member", Target = "~M:ShareMyAdventures.Application.UseCases.Participants.Queries.ListParticipantsQueryHandler.Handle(ShareMyAdventures.Application.UseCases.Participants.Queries.ListWithPagingParticipantsQuery,System.Threading.CancellationToken)~System.Threading.Tasks.Task{ShareMyAdventures.Application.UseCases.Participants.Queries.ListParticipantsResponse}")]
[assembly: SuppressMessage("Major Code Smell", "S6966:Awaitable method should be used", Justification = "<Pending>", Scope = "member", Target = "~M:ShareMyAdventures.Application.UseCases.Participants.Queries.ListParticipantsQueryHandler.Handle(ShareMyAdventures.Application.UseCases.Participants.Queries.ListWithPagingParticipantsQuery,System.Threading.CancellationToken)~System.Threading.Tasks.Task{ShareMyAdventures.Application.Common.Models.Result{ShareMyAdventures.Application.Common.Models.PagedData{ShareMyAdventures.Application.UseCases.Participants.Queries.ParticipantView}}}")]
